import { NextRequest, NextResponse } from "next/server";
import { getCollection } from "@/lib/mongodb";
import { Entry } from "@/lib/types";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const person = searchParams.get("person") as "Karthik" | "Likhita" | null;

    const collection = await getCollection<Entry>("entries");
    const query: any = person ? { person } : {};

    const entries = await collection
      .find(query)
      .sort({ date: -1 })
      .toArray();

    // Calculate summary
    const totalIncome = entries.filter(e => e.type === "income").reduce((sum, e) => sum + e.amount, 0);
    const totalExpense = entries.filter(e => e.type === "expense").reduce((sum, e) => sum + e.amount, 0);
    const balance = totalIncome - totalExpense;

    const exportDate = new Date().toISOString().slice(0, 10);
    const filename = `expense-tracker-${person || "all"}-${exportDate}.csv`;

    // Build CSV with proper formatting
    let csv = "";

    // Header Section
    csv += "================================\n";
    csv += `EXPENSE TRACKER - EXPORT REPORT\n`;
    csv += "================================\n";
    csv += `Export Date:,${exportDate}\n`;
    csv += `User:,${person || "All Users"}\n`;
    csv += `Total Records:,${entries.length}\n`;
    csv += "\n";

    // Summary Section
    csv += "FINANCIAL SUMMARY\n";
    csv += "================================\n";
    csv += `Total Income:,₹${totalIncome.toFixed(2)}\n`;
    csv += `Total Expense:,₹${totalExpense.toFixed(2)}\n`;
    csv += `Net Balance:,₹${balance.toFixed(2)}\n`;
    csv += "\n";

    // Transactions Section
    csv += "TRANSACTION DETAILS\n";
    csv += "================================\n";
    csv += "Date,Day,Type,Category,Amount (₹),Person,Note\n";

    entries.forEach(entry => {
      const date = new Date(entry.date);
      const dayName = date.toLocaleDateString('en-US', { weekday: 'short' });
      const note = (entry.note || "").replace(/,/g, ";").replace(/"/g, "'");
      const type = entry.type === "income" ? "INCOME" : "EXPENSE";

      csv += `${entry.date},${dayName},${type},${entry.category},${entry.amount},${entry.person},"${note}"\n`;
    });

    // Footer
    csv += "\n";
    csv += "================================\n";
    csv += "Generated by Expense Tracker App\n";
    csv += `Report End\n`;
    csv += "================================\n";

    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
